### ISSUE TITLE
unable to get docker image 

### ISSUE THREAD

**Issue by grwilson** [delphix/appliance-build#379]
Build failure with the following error:

```
11:48:44  <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
11:48:44  <127.0.0.1> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
11:48:44  <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1571161721.32-202796222788724 `" && echo ansible-tmp-1571161721.32-202796222788724="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1571161721.32-202796222788724 `" ) && sleep 0'
11:48:44  Using module file /usr/lib/python2.7/dist-packages/ansible/modules/commands/command.py
11:48:44  <127.0.0.1> PUT /home/ubuntu/.ansible/tmp/ansible-local-2240a57UvB/tmpiSC5ZR TO /home/ubuntu/.ansible/tmp/ansible-tmp-1571161721.32-202796222788724/AnsiballZ_command.py
11:48:44  <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1571161721.32-202796222788724/ /home/ubuntu/.ansible/tmp/ansible-tmp-1571161721.32-202796222788724/AnsiballZ_command.py && sleep 0'
11:48:44  <127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-mzfhagcvfmepbrhxhtxcuumxhknnajik; /usr/bin/python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1571161721.32-202796222788724/AnsiballZ_command.py'"'"' && sleep 0'
11:48:52  <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1571161721.32-202796222788724/ > /dev/null 2>&1 && sleep 0'
11:48:52  fatal: [localhost]: FAILED! => {
11:48:52      "changed": true, 
11:48:52      "cmd": "docker build --network host --tag \"appliance-build:latest\" \"/var/tmp/jenkins/workspace/devops-gate/master/appliance-build-stage1/6.0/release/post-push/appliance-build/docker\"", 
11:48:52      "delta": "0:00:09.427315", 
11:48:52      "end": "2019-10-15 17:48:50.864415", 
11:48:52      "invocation": {
11:48:52          "module_args": {
11:48:52              "_raw_params": "docker build --network host --tag \"appliance-build:latest\" \"/var/tmp/jenkins/workspace/devops-gate/master/appliance-build-stage1/6.0/release/post-push/appliance-build/docker\"", 
11:48:52              "_uses_shell": true, 
11:48:52              "argv": null, 
11:48:52              "chdir": null, 
11:48:52              "creates": null, 
11:48:52              "executable": null, 
11:48:52              "removes": null, 
11:48:52              "stdin": null, 
11:48:52              "warn": true
11:48:52          }
11:48:52      }, 
11:48:52      "msg": "non-zero return code", 
11:48:52      "rc": 1, 
11:48:52      "start": "2019-10-15 17:48:41.437100", 
11:48:52      "stderr": "free(): invalid pointer\nSIGABRT: abort\nPC=0x7fe5059a8e97 m=0 sigcode=18446744073709551610\nsignal arrived during cgo execution\n\ngoroutine 1 [syscall, locked to thread]:\nruntime.cgocall(0x4afd50, 0xc420049cc0, 0xc420049ce8)\n\t/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420049c90 sp=0xc420049c50\ngithub.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0xbfada0)\n\tgithub.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420049cc0 sp=0xc420049c90\ngithub.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0xbfada0)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420049cf8 sp=0xc420049cc0\ngithub.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420010390)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420049da0 sp=0xc420049cf8\ngithub.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420049e88, 0x410022, 0xc4200102f0)\n\t<autogenerated>:4 +0x46 fp=0xc420049de0 sp=0xc420049da0\ngithub.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420049e68 sp=0xc420049de0\ngithub.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffebd745d4e, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420049ed8 sp=0xc420049e68\ngithub.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420049f58 sp=0xc420049ed8\nmain.main()\n\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420049f88 sp=0xc420049f58\nruntime.main()\n\t/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420049fe0 sp=0xc420049f88\nruntime.goexit()\n\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420049fe8 sp=0xc420049fe0\n\ngoroutine 17 [syscall, locked to thread]:\nruntime.goexit()\n\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1\n\nrax    0x0\nrbx    0x7ffebd7441c0\nrcx    0x7fe5059a8e97\nrdx    0x0\nrdi    0x2\nrsi    0x7ffebd743f50\nrbp    0x7ffebd7442c0\nrsp    0x7ffebd743f50\nr8     0x0\nr9     0x7ffebd743f50\nr10    0x8\nr11    0x246\nr12    0x7ffebd7441c0\nr13    0x1000\nr14    0x0\nr15    0x30\nrip    0x7fe5059a8e97\nrflags 0x246\ncs     0x33\nfs     0x0\ngs     0x0\nreceived unexpected HTTP status: 503 Service Unavailable", 
11:48:52      "stderr_lines": [
11:48:52          "free(): invalid pointer", 
11:48:52          "SIGABRT: abort", 
11:48:52          "PC=0x7fe5059a8e97 m=0 sigcode=18446744073709551610", 
11:48:52          "signal arrived during cgo execution", 
11:48:52          "", 
11:48:52          "goroutine 1 [syscall, locked to thread]:", 
11:48:52          "runtime.cgocall(0x4afd50, 0xc420049cc0, 0xc420049ce8)", 
11:48:52          "\t/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420049c90 sp=0xc420049c50", 
11:48:52          "github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0xbfada0)", 
11:48:52          "\tgithub.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420049cc0 sp=0xc420049c90", 
11:48:52          "github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0xbfada0)", 
11:48:52          "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420049cf8 sp=0xc420049cc0", 
11:48:52          "github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420010390)", 
11:48:52          "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420049da0 sp=0xc420049cf8", 
11:48:52          "github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420049e88, 0x410022, 0xc4200102f0)", 
11:48:52          "\t<autogenerated>:4 +0x46 fp=0xc420049de0 sp=0xc420049da0", 
11:48:52          "github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)", 
11:48:52          "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420049e68 sp=0xc420049de0", 
11:48:52          "github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffebd745d4e, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)", 
11:48:52          "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420049ed8 sp=0xc420049e68", 
11:48:52          "github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)", 
11:48:52          "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420049f58 sp=0xc420049ed8", 
11:48:52          "main.main()", 
11:48:52          "\t/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420049f88 sp=0xc420049f58", 
11:48:52          "runtime.main()", 
11:48:52          "\t/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420049fe0 sp=0xc420049f88", 
11:48:52          "runtime.goexit()", 
11:48:52          "\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420049fe8 sp=0xc420049fe0", 
11:48:52          "", 
11:48:52          "goroutine 17 [syscall, locked to thread]:", 
11:48:52          "runtime.goexit()", 
11:48:52          "\t/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1", 
11:48:52          "", 
11:48:52          "rax    0x0", 
11:48:52          "rbx    0x7ffebd7441c0", 
11:48:52          "rcx    0x7fe5059a8e97", 
11:48:52          "rdx    0x0", 
11:48:52          "rdi    0x2", 
11:48:52          "rsi    0x7ffebd743f50", 
11:48:52          "rbp    0x7ffebd7442c0", 
11:48:52          "rsp    0x7ffebd743f50", 
11:48:52          "r8     0x0", 
11:48:52          "r9     0x7ffebd743f50", 
11:48:52          "r10    0x8", 
11:48:52          "r11    0x246", 
11:48:52          "r12    0x7ffebd7441c0", 
11:48:52          "r13    0x1000", 
11:48:52          "r14    0x0", 
11:48:52          "r15    0x30", 
11:48:52          "rip    0x7fe5059a8e97", 
11:48:52          "rflags 0x246", 
11:48:52          "cs     0x33", 
11:48:52          "fs     0x0", 
11:48:52          "gs     0x0", 
11:48:52          "received unexpected HTTP status: 503 Service Unavailable"
11:48:52      ], 
11:48:52      "stdout": "Sending build context to Docker daemon  4.608kB\r\r\nStep 1/13 : FROM ubuntu:bionic-20180426", 
11:48:52      "stdout_lines": [
11:48:52          "Sending build context to Docker daemon  4.608kB", 
11:48:52          "", 
11:48:52          "Step 1/13 : FROM ubuntu:bionic-20180426"
11:48:52      ]
11:48:52  }
```

This is a failure to download the docker image from docker hub

**Comment by prashks** [comment]
Another instance over the weekend: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-stage1/job/master/job/post-push/22616/consoleFull

**Comment by pzakha** [comment]
Closing this as we removed docker from the build.
